### ISSUE TITLE
Confusing error when src/main/webapp/appengine-web.xml not found

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/app-gradle-plugin#159]
I'm following the instructions at https://cloud.google.com/appengine/docs/standard/java/tools/gradle, but had forgotten to add an `appengine-web.xml`.  `gradle appengineRun` produces a very confusing error message.  I initially tried with Gradle 2.12 and thought the plugin might require a different version and so tried 4.1, to the same effect.

```sh
$ ls src/main/webapp/WEB-INF/
web.xml

$ gradle appengineRun

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bsd/Manumitting/Projects/GooglePluginEclipse/test-projects/gradle-app-engine-standard/build.gradle' line: 32

* What went wrong:
A problem occurred evaluating root project 'gradle-app-engine-standard'.
> Could not find method run() for arguments [build_7nfq7n4xs7v418q9yllpwyn3u$_run_closure3$_closure5@74e5d752] on object of type com.google.cloud.tools.gradle.appengine.core.AppEngineExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by loosebazooka** [comment]
The root of this problem is in auto-detection of flex/standard. If detected as standard, it builds a extension for gradle that include a `run` extension. Otherwise it doesn't create the `run` extension under the `appengine`extesion <--- this is the error you get because it cant resolve "run" in the build file (the flex plugin doesn't define run)

The fix for better errors is to perhaps print out the detected project structure or something during auto-detection so user's know what's up.

The other thing you can do is force the type you want to apply (which would be more straightforward).

```
apply plugin: "com.google.cloud.tools.appengine-standard"
// or
apply plugin: "com.google.cloud.tools.appengine-flexible"
```
