### ISSUE TITLE
Gradle task appengineDeploy also tries to deploy endpoints dependencies

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/app-gradle-plugin#85]
Hi,
I've got an Android project with one main backend and one flexible backend, both using Cloud Endpoints. The main backend has endpointsServer dependency on the flexible backend (using the new endpoints gradle plugin). When deploying the main backend, the gradle task also tries to deploy the flexible backend after deploying the main backend. I don't know if this is related to the endpoint dependency yet.

**Comment by patflynn** [comment]
@Burtan can you provide a skeleton project to reproduce?  How are you invoking the deploy task?

**Comment by Burtan** [comment]
I'm invoking the deploy task via the Android Studio GUI

**Comment by loosebazooka** [comment]
This plugin isn't quite compatible with Android Studio yet. So the Android Studio GUI presumably will act in unpredictable ways. Are you still using the old plugin as well?

**Comment by Burtan** [comment]
I'm not using the old plugin anymore. I'm invoking it via the gradle Android Studio GUI on the right side. Not via the menu -> build -> deploy. I think that should be the same as typing the task into the terminal?

**Comment by loosebazooka** [comment]
Oh, yeah Intellij's handling of gradle tasks isn't intuitive, it actually just runs the task on the root project.

So what you might think is 
```
./gradlew :mainBackend:deploy
```

is actually
```
./gradlew deploy
```

So it ends up running `deploy` on all modules in the project.

I can't think of any good options, but some mediocre options are:
1. Clicking on `deploy` a run configuration that you can modify and run from the `run configurations` menu (instead of gradle side bar)
2. Create a custom unique task in each module (that depends on deploy), then that task will be clickable in the window but only run deploy on the module you're clicking on
3. File a bug against intellij, https://github.com/JetBrains/intellij-community and wait for the fix to propagate down to android studio?

**Comment by Burtan** [comment]
Yeah, you are right. Running deploy from terminal is totally fine. Ridiculous behaviour from IntelliJ, but certainly this is not the right spot to address that ;-). Thanks for the suggestions anyway!
