### ISSUE TITLE
Can't uploading cron jobs using the plugin

### ISSUE THREAD

**Issue by hookenwu** [GoogleCloudPlatform/app-gradle-plugin#88]
Dear,  I have develop an app engine backend project in Android Studio, I have transfer to this new plugin in stead of the old one.

Everything seems ok except the cron jobs... If I use the command `gradle appengineDeploy`, it seems that the cron jobs will not be uploaded. If I use the command integrated in the Android Studio, then the cron jobs successful uploaded.

Is there anything I need to modify the configuration file for cron jobs? 
Many TKS :)

**Comment by patflynn** [comment]
Thanks for your report @hookenwu.

@loosebazooka should we open an issue to improve docs for this?  Do they go on github, codesite, or both?

**Comment by loosebazooka** [comment]
@hookenwu yes you are correct. The new flow doesn't actually upload cron.xml/yaml anymore, because cron.xml/yaml is global for the project, not just the module you are uploaded.

The easiest way to do this is to just upload the cron.yaml yourself from the staged-app directory.

```
./gradlew appengineStage
gcloud app deploy build/staged-app/cron.yaml
```

Of course if you wanted to do this directly with gradle, you could modify the `deployables` parameter in the appengine.deploy configuration.

**Comment by loosebazooka** [comment]
@hookenwu the next version based on #112 should be out in the near future and you can just configure this easily from the plugin.

**Comment by loosebazooka** [comment]
@hookenwu v1.3.0-rc1 and moving forward expose appengineDeployCron and other tasks to do configuration deployment.

The command integrated into android studio uses an older deployment mechanism and that's why it works for you like that.
 
To auto deploy, just create a task dependency in your build file.
```
appengineDeploy.dependsOn appengineDeployCron
```

and cron will be deployed when you deploy your app.
